services:
  ollama:
    image: docker.io/ollama/ollama:latest
    volumes:
      - ./.docker/ollama:/root/.ollama
    container_name: ollama
    tty: true
    ports:
      - 11434:11434
    networks:
      - synui_app
